config/routes.rb
Reps::Application.routes.draw do
  devise_for :users
  get 'main/index'
  root to: 'main#index'

  match '/save_report.json', to: 'employee#save_report', via: [:post]
  get "/myreports", to: "employee#user_reports", as: "user_reports"
  get "/myreport/:id", to: "employee#user_report", as: "user_report"
  get "/blocked", to: "employee#blocked", as: "user_blocked"

  match '/get_report.json', to: 'manager#get_report', via: [:post]
  match '/change_employee.json', to: 'manager#change_day_of_report', via: [:post]
  match '/change_employee_status.json', to: 'manager#change_status', via: [:post]
  get "/employees", to: "manager#list_employees", as: "list_employees"
  match '/invite_user.json', to: 'manager#invite_user', via: [:post]
end

app/models/answer.rb
class Answer < BaseModel
  field :answers, type: Array, default: [];

  belongs_to :report
  belongs_to :question

end

app/models/base_model.rb
class BaseModel
  include Mongoid::Document

  def as_json(options={})
    attrs = super(options)
    attrs["id"] = attrs["_id"]
    attrs
  end
end

app/models/question.rb
class Question < BaseModel
  field :text, type: String

  has_many :answers
end

app/models/report.rb
class Report < BaseModel
  field :created_at, as: :datetime, type: ActiveSupport::TimeWithZone, default: -> { Time.now.in_time_zone }

  scope :reports_from_employee, ->(user_id) { where(user_employee_id: user_id).order_by(created_at: :desc)}
  scope :reports_to_manager, ->(user_id) { where(user_manager_id: user_id).order_by(created_at: :desc)}

  has_many :answers
  belongs_to :user_manager, class_name: 'User', inverse_of: :report_manager
  belongs_to :user_employee, class_name: 'User', inverse_of: :report_employee

end

app/models/user.rb
class User < BaseModel
  include Mongoid::Timestamps
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validate :nickname_validations, presence: true

  field :email, type: String, default: ""
  field :nickname, type: String, default: ""
  field :time_zone, type: String, default: "UTC"
  field :notification_time,  type: Time, default: -> {Time.now - 1.day}
  field :manager, type: Boolean, default: false
  field :status, type: Boolean, default: true
  field :day_of_report, type: Integer, default: 5
  #Time.now.in_time_zone.wday
  field :mood, type: String, default: "Good"
  field :encrypted_password, type: String, default: ""
  field :current_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token, type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,       type: Integer, default: 0
  field :current_sign_in_at,  type: Time
  field :last_sign_in_at,     type: Time
  field :current_sign_in_ip,  type: String
  field :last_sign_in_ip,     type: String

  def nickname_validations
    errors.add(:nickname, 'can\'t be empty') if nickname.blank?
    errors.add(:nickname, 'can\'t contain less than 3 symbols') if nickname.size < 3
    nickname = self.nickname.split
    errors.add(:nickname, 'can\'t contain more than 2 words') if nickname.size > 2
    if nickname.size == 2
      errors.add(:nickname, '1 part can\'t contain more than 12 symbols') if nickname[0].size > 12
      errors.add(:nickname, '2 part can\'t contain more than 12 symbols') if nickname[1].size > 12
    elsif nickname.size == 1
      errors.add(:nickname, 'can\'t contain more than 12 symbols') if nickname[0].size > 12
    end
  end

  has_many :report_manager, class_name: 'Report', inverse_of: :user_manager
  has_many :report_employee, class_name: 'Report', inverse_of: :user_employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_time_zone

  def set_time_zone
    Time.zone = current_user.time_zone if current_user
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :nickname, :time_zone) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :current_password, :password, :password_confirmation, :nickname, :time_zone) }
  end

  protect_from_forgery with: :exception
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  before_filter :authenticate_user!
  before_filter :status_true?

  def save_report
    report = Report.new(user_manager_id: report_params["manager_id"], user_employee_id: current_user.id)
    current_user.mood = report_params["mood"]
    current_user.save
    report_params["answ"].each do |answers|
      answer = Answer.new(question_id: answers[0])
      answers[1].each do |answ|
        answer.answers << answ[1]
      end
      answer.report_id = report.id
      return render :json => { :errors => answer.errors.full_messages } unless answer.save
    end
    return render :json => { :errors => report.errors.full_messages } unless report.save
    UserMailer.report(report).deliver
    render :json => { :errors => false }
  end

  def user_reports
    @reports = Report.reports_from_employee(current_user.id)

    respond_to do |format|
      format.html { render "employee/reports" }
    end
  end

  def user_report
    @report = Report.find_by(id: params['id'])

    respond_to do |format|
      format.html { render "employee/report" }
    end
  end

  private
  def report_params
    params.permit!
  end

  def status_true?
    if current_user and !current_user.status
      respond_to do |format|
        format.html { render "employee/blocked" }
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_blocked?

  def index
    if current_user.manager
      @reports = Report.reports_to_manager(current_user.id)
      respond_to do |format|
        format.html { render "manager/index" }
      end
    else
      @manager = User.where(manager: true).first
      @report = Report.reports_from_employee(current_user.id).first
      @questions = Question.all
      respond_to do |format|
        format.html { render "employee/index" }
      end
    end
  end

  private
  def user_blocked?
    if current_user and !current_user.status
      respond_to do |format|
        format.html { render "employee/blocked" }
      end
    end
  end

end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_filter :authenticate_user!

  def get_report
    report = Report.find_by(id: params['id_report'])
    answers = {}
    report.answers.each do |answ_quest|
      answers[answ_quest.question.text] = answ_quest.answers
    end

    render :json => { :date => report.created_at.to_s(:my_datetime),
                      :user => report.user_employee.nickname,
                      :answers => answers
    }
  end

  def list_employees
    @users = User.nin(id: current_user.id).order_by(created_at: :desc)

    respond_to do |format|
      format.html { render "manager/employees" }
    end
  end

  def change_day_of_report
    user = User.find_by(id: params['user_id'])
    day = Date::DAYNAMES.index(params['day'])
    user.day_of_report = day
    return render :json => { :errors => true } unless user.save
    render :json => { :errors => false }
  end

  def change_status
    user = User.find_by(id: params['user_id'])
    user.status = params['status_id']!= "ON"
    return render :json => { :errors => true } unless user.save
    render :json => { :errors => false }
  end

  def invite_user
    return render :json => { :errors => true } if User.find_by(email: params['email'])
    UserMailer.invite(current_user, params['email']).deliver
    render :json => { :errors => false }
  end

  private
  def report_params
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employee/blocked.html.haml
.col-lg-5.col-lg-offset-4#reps
  .row.col-lg-offset-1#my_reports
    %label
      Your account has been blocked. Please contact to manager - js22908@gmail.com

app/views/employee/index.html.haml
%h3
  Weekly Report
.row
  - unless @report.blank?
    #last_report.col-lg-9.col-lg-offset-2
      %label{:style => "font-size:18px;float:right"}
        Last report
      %label= @report.created_at.to_s(:my_datetime)
      - @report.answers.each do |qest_answ|
        .row
          %label.col-lg-offset-3= qest_answ.question.text
          %ul
            - qest_answ.answers.each do |answer|
              %li
                = answer
%input#new-report-show.col-lg-offset-6.btn.btn-success.btn-lg{type: "button", value: "NEW REPORT"}
.row#new_report{:style => "display:none"}
  .col-lg-offset-2
    .row.new-report-form.col-lg-11
      %form#create-report-form.form-horizontal{action: "/interview", method: "post", role: "form"}
        .row
          %label{:style => "font-size:18px"}
            QUESTIONS:
          %label{:style => "float:right"}
            Your manager: #{@manager.nickname}
            %br
            (#{@manager.email})
        .col-lg-offset-1
          - @questions.each do |question|
            .form-group.answers{:id => "#{question.id}"}
              %label{for: "InputAnswer1"} #{question.text}
              %input#InputAnswer1.form-control{name: "#{question.id}[0]", placeholder: "Enter answer of question", type: "text"}/
              %button.more-answer.btn.btn-primary.btn-xs{type: "button"} one more answer
          .form-group
            %label{for: "mood"} How would you rate your current mood?
            .col-lg-2.col-lg-offset-3
              %select.form-control#mood{:name => "mood"}
                %option{:selected=>"selected"}
                  Super
                %option{:name => "mood"}
                  Good
                %option{:name => "mood"}
                  Bad
          %input{name: "manager_id", type: "hidden", value: "#{@manager.id}"}
          .row.col-lg-3
            %button#create-report-send.btn.btn-success.btn-sm{type: "button"} SUBMIT REPORT

app/views/employee/report.html.haml
%h3
  Weekly Report
.row
  #last_report.col-lg-9.col-lg-offset-2
    %label= @report.created_at.to_s(:my_datetime)
    = link_to "All Reports", user_reports_path, :class => "col-lg-offset-8 btn btn-primary"
    - @report.answers.each do |qest_answ|
      .row
        %label.col-lg-offset-3= qest_answ.question.text
        %ul
          - qest_answ.answers.each do |answer|
            %li
              = answer

app/views/employee/reports.html.haml
.col-lg-5.col-lg-offset-4#reps
  .row.col-lg-offset-4#my_reports
    - if @reports.blank?
      %label{:style => 'font-size:18px;margin-left: -17px;'}
        You havent reports
    - else
      %label{:style => 'font-size:18px;margin-left: -17px;'}
        All My Reports:
      - @reports.each do |report|
        .row.report{:id => "#{report.id}"}
          = link_to("#{report.created_at.to_s(:my_datetime)}", user_report_path(report.id))

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title WeeklyReps
    %meta{charset: "utf-8"}/
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Oswald|Open+Sans:400,600,700", media: "all"
    = javascript_include_tag "application"
  %body
    %header.navbar.navbar-default.navbar-fixed-top{role: "banner"}
      .navbar-header
        = link_to "The Weekly Reps", root_path, :class=>"navbar-brand"
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
          - if user_signed_in?
            - if current_user.manager
              %li= link_to("List of employees".upcase!, list_employees_path)
            - else
              %li= link_to("My reports".upcase!, user_reports_path)
      %ul.nav.navbar-nav.navbar-right
        #button_sign
          - if user_signed_in?
            = link_to 'Sign out', destroy_user_session_path, :method => :delete, :class=>"btn btn-li btn-danger"
          - else
            = link_to 'Sign in', new_user_session_path, :class=>"btn btn-li btn-success"
    .container
      = yield

app/views/manager/employees.html.haml
.col-lg-6.col-lg-offset-3
  .row.col-lg-offset-1
    %label Add employee:
    %input#add-employee{type: "text", :placeholder => "example@example.com"}/
  %button#add-employee-submit.col-lg-offset-3.btn.btn-primary{type: "button"} ADD
  #result
.col-lg-9.col-lg-offset-2#reps
  .row#employyes
    - if @users.blank?
      %label.col-lg-offset-4{:style => 'font-size:18px;'}
        You havent employees that send you their reports
    - else
      %label.col-lg-offset-4{:style => 'font-size:18px'}
        Your Employees :
      %table.table.table-bordered#employees-list
        %thead
          %tr
            %th.status
              Status
            %th.name
              Name
            %th
              Email
            %th.day
              Day of report
            %th.mood_th
              Mood
        %tbody
          - @users.each do |user|
            %tr.user{:id => "#{user.id}"}
              %td
                - if user.status
                  .change-status.status-on#ON
                - else
                  .change-status.status-off#OFF
              %td
                %label
                  = user.nickname
              %td
                %label
                  = user.email
              %td
                %select.form-control.day_of_report
                  - Date::DAYNAMES[0..7].each do |day|
                    - if day == Date::DAYNAMES[user.day_of_report]
                      %option{:selected=>"selected"}
                        = day
                    - else
                      %option
                        = day
              %td
                - if user.mood == "Super"
                  = image_tag("mood_cool.png", :class => 'mood')
                - elsif user.mood == "Good"
                  = image_tag("mood_good.png", :class => 'mood')
                - else
                  = image_tag("mood_bad.png", :class => 'mood')

app/views/manager/index.html.haml
.col-lg-9.col-lg-offset-2#reps
  .row#my_reports
    - if @reports.blank?
      %label.col-lg-offset-4{:style => 'font-size:18px;'}
        You havent reports
    - else
      %label.col-lg-offset-4{:style => 'font-size:18px'}
        Received Reports :
      %table.table.table-bordered#allreports
        %thead
          %tr
            %th
              Date
            %th.answer
              Name
            %th.date
              Email
        %tbody
          - @reports.each do |report|
            %tr.report{:id => "#{report.id}"}
              %td
                = report.created_at.to_s(:my_datetime)
              %td
                = report.user_employee.nickname
              %td
                = report.user_employee.email
#userreport
%script#report-template{type: "text/template"}
  .row
    #last_report.col-lg-9.col-lg-offset-2
      %label
        {{date}}
      %label.col-lg-offset-6
        from {{user}}
      .row.quest_answ

%script#report-template-quesion{type: "text/template"}
  %label.col-lg-offset-2
    {{question}}
  %ul.answs

%script#report-template-answer{type: "text/template"}
  %li
    {{answer}}

app/views/notifications/intive.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div class="row">
  <label>Hi,</label>
  <br>
  <label><%= @user.email%> invites you to WeeklyReps <%= link_to("registrate", new_user_registration_path, :host => "hidden-island-8670.herokuapp.com")%> for sending weekly reports</label>
</div>
</body>
</html>

app/views/notifications/invite.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div class="row">
  <label>Hi,</label>
  <br>
  <label><%= @user.email%> invites you to WeeklyReps <%= link_to("registrate", new_user_registration_path, :host => "hidden-island-8670.herokuapp.com")%> for sending weekly reports</label>
</div>
</body>
</html>

app/views/notifications/report.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div class="row">
  <label>Hello, <%= @report.user_manager.nickname%>.</label>
  <br>
  <label><%= @report.user_employee.nickname%> sent you own weekly report.</label>
  <h3><%= link_to("Weekly Report", root_path, :host => "hidden-island-8670.herokuapp.com")%></h3>
  <label><%= @report.created_at.to_s(:my_datetime)%></label>
  <br>
  <%- @report.answers.each do |qest_answ|%>
    <%= qest_answ.question.text%>
    <ul>
      <%- qest_answ.answers.each do |answer|%>
        <li><%= answer%></li>
      <%end%>
    </ul>
  <%end%>
</div>
</body>
</html>

app/views/notifications/weekly.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div class="row">
  <h3>Report Due Tomorrow</h3>
  <label>Hi <%= @user.nickname%></label>
  <br>
  <label>This is a reminder that your WeeklyReps report is due tomorrow</label>
  <%= link_to("Submit Report", root_path, :host => "hidden-island-8670.herokuapp.com")%>
</div>
</body>
</html>

app/views/notifications/weekly.text.erb
Report Due Tomorrow

Hi

This is a reminder that your 15Five report is due tomorrow.

Submit Report